version: '3.8'

services:
  bot:
    build: .
    container_name: highfocus-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./highfocus.db:/app/highfocus.db
      - ./bot.log:/app/bot.log
    environment:
      - PYTHONUNBUFFERED=1
    # Автоматический перезапуск
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

